version: '3.8'

services:
  tally:
    build: .
    container_name: ObsTally
    image: wiibleyde/tally:latest
    restart: always
    ports:
      - 7070:8080
    volumes:
      - /var/tally/data/:/root/data/
      - /var/tally/logs/:/root/logs/