version: '3.8'

services:
  web:
    build: .
    image: wiibleyde/tally:latest
    container_name: tally
    restart: always
    ports:
      - "9124:5000"
    volumes:
      - /var/tally/data:/app/data:rw