version: '3.8'

services:
  api:
    build: .
    container_name: TallyGo
    image: wiibleyde/tally:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./tally.json:/root/tally.json:rw